# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gull Docs
baseurl: "" # the subpath of your site, e.g. /blog
# Build settings
include: ['_pages']
version: 1.4.2
sidebar_groups:
  - id: user
    name: User Guide
    index: user-guide